openapi: 3.0.0
info:
  title: "APIs For OrdersPackPHPTest"
  contact:
    name: Developer
    url: "https://boosurostephen.com"
    email: boosurostephen@yahoo.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: 1.0.0
schemes:
  - http
  - https
servers:
  - url: "http://127.0.0.1:8000"
    description: "PHP TEST API Server"
paths:
  /api/v1/products:
    get:
      tags:
        - Products
      summary: "Fetch All Products"
      description: "Get list of products"
      operationId: 7ad42b1da991a569902fe0f55ffc7540
      responses:
        200:
          description: "successful operation"
      security:
        - BearerAuth: []
  "/api/v1/products/{id}":
    get:
      tags:
        - Products
      summary: "Fetch a Product"
      description: "Fetch a product"
      operationId: dd744d0ef909a4622bb5eda129cc7140
      parameters:
        - name: id
          in: path
          description: "Product id"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: "successful operation"
        401:
          description: Unauthorised
      security:
        - BearerAuth: []
  /api/v1/login:
    post:
      tags:
        - Users
      summary: "Login User"
      operationId: 04edf01e45db5894b023de5590901cd1
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: string
        - name: password
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: "successful operation"
components:
  securitySchemes:
    BearerAuth:
      type: http
      description: "A short description for security scheme"
      name: Authorization
      in: header
      bearerFormat: JWT
      scheme: bearer
